### PR TITLE
Added in an important comma

### PR DESCRIPTION
**Pull request by BazzerDv**
You forgot a comma which stopped the game from working

### CODE REVIEW

**Review by JoeMusashi9999 — APPROVED** [review]
Thanks so much for the help! I always wondered why that specific aspect was breaking all the time!

**Comment by BazzerDv** [comment]
So are you gonna merge it or...

**Comment by JoeMusashi9999** [comment]
Did! Thanks so much for the commit!

**Comment by BazzerDv** [comment]
The repository hasn't updated tho?

**Comment by JoeMusashi9999** [comment]
Ahh, I accepted but didn't merge sorry.

**Pull request merged**
